#!/bin/bash
source functions.pine
name=pine_ovz
artifact="rootfs_${name}.tgz"
artifact_repo="untoreh/pine"
delta="delta_ovz"
rootfs=rootfs
ref="trunk"

## confirm we made a new tree
if [ ! "`find ${name}_tree/* -maxdepth 0 | wc -l`" -gt 0 ] ; then
    echo "newer tree not grown. (tree folder is empty)"
    exit 1
fi

install_tools "ostree wget"

## rootfs has the ostree repo
fetch_artifact $artifact_repo $artifact $rootfs

## now commit the new tree to the repo
rev=$(ostree --repo=$rootfs/ostree/repo commit -s $(date)'-build' -b $ref --tree=dir=${name}_tree)

## then generate the delta and archive it
ostree --repo=$rootfs/ostree/repo static-delta generate $ref --inline --min-fallback-size 0 --filename=${rev}

## archive
tar cf ${delta}.tar $rev