#!/bin/sh

## use edge packages for docker and etcd to avoid hard coding init services,
## also terraform lags behind in updates and does not include any additional configs, so
## install it manually

## DOCKER
#`apk info -R docker | sed '/so:/q' | tail -n +4 | head -n -1` \
#DOCKER_VERSION=`last_version docker/docker`
#wget -q https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz -O docker.tgz
#tar xf docker.tgz
#mv docker/docker* usr/bin/
#rm -rf docker docker.tgz
#adduser -D docker

## ETCD
#ETCD_VERSION=`last_version coreos/etcd`
#wget -q https://github.com/coreos/etcd/releases/download/v$ETCD_VERSION/etcd-v$ETCD_VERSION-linux-amd64.tar.gz -O etcd.zip
#tar xf etcd.zip
#mkdir -p usr/bin
#mv etcd*/etcd* usr/bin
#rm -rf etcd*

## TERRAFORM
TERRAFORM_VERSION=`last_version hashicorp/terraform`
wget -q https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terra.zip
unzip terra.zip
mv terraform usr/bin
rm -rf terra.zip

## LOCKSMITH
LOCKSMITH_VERSION=`last_version coreos/locksmith`
wget -q https://github.com/coreos/locksmith/archive/v${LOCKSMITH_VERSION}.tar.gz -O locksmith.tar.gz
tar xf locksmith.tar.gz
cd locksmith* && ./build && mv bin/locksmithctl ../usr/bin && ln -sr ../usr/bin/locksmithctl ../usr/bin/locksmithd && cd -
rm -rf locksmith*

## use alpine packages
apkc docker etcd

../compress.pine $PWD/usr/bin/terraform $PWD/usr/bin/docker* $PWD/usr/bin/etcd*
