#!/bin/sh

## this file must be sourced to operate in the correct directory

## RUNC
runc_repo="opencontainers/runc"
RUNC_VERSION=$(last_release $runc_repo rc)
fetch_artifact $runc_repo:$RUNC_VERSION ".*linux.*64.*" - >usr/bin/runc

## CONSUL
consul_repo="hashicorp/consul"
CONSUL_VERSION=$(last_version $consul_repo)
consul_url="https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip"
fetch_artifact $consul_url usr/bin