#!/bin/sh

case "$1" in
    -a )
    device=`find /dev 2>/dev/null | grep -E "/vd.*|/sd.*|/hd.*" | sort | head -n1` ;;
    '' )
    echo "-a uses the first device found, or specify a device path."
    exit ;;
    * )
    device=$1 ;;
esac

## get busybox for rebooting
mkdir pivot && mount -t tmpfs tmpfs pivot && cd pivot
wget https://www.busybox.net/downloads/binaries/1.26.2-defconfig-multiarch/busybox-x86_64 -O busybox
chmod +x busybox

## get image url
img_url=`wget -qO- https://api.github.com/repos/untoreh/pine/releases | grep browser_download_url | grep image.pine | head -n 1 | cut -d '"' -f 4`
echo $img_url

wget -qO- $img_url | tar xz -O | dd of=$device bs=512 conv=notrunc,fsync ; ./busybox reboot
