#!/bin/bash

source functions.pine

## get previous release
# prevV=`pine_version` ## remotely
prevV=`git tag --sort=committerdate | tail -1` ## locally

## prev date
prevD=`echo $prevV | cut -d- -f1`
## prev build number
prevN=`echo $prevV | cut -d- -f2`
## gen new release number
newD=`date +%y.%m`
if [ $prevD = $newD ]; then
    newN=$((prevN + 1))
else
    newN=0
fi
export newV=$newD-$newN
printc "$newV is the new version"

## tree init
mkdir -p /srv/tree
cd /srv/tree

while `mountpoint -q ./proc`; do
    umount proc
done
while `mountpoint -q ./dev`; do
    umount dev
done
while `mountpoint -q ./sys`; do
    umount sys
done

rm -rf ./*

mkdir -p dev sys proc run boot var/home var/mnt var/opt var/srv var/roothome sysroot/ostree sysroot/tmp usr/bin usr/sbin usr/lib usr/lib64 usr/etc

## links
ln -s usr/etc etc
ln -s var/home home
ln -s var/roothome root
ln -s var/mnt mnt
ln -s var/opt opt
ln -s var/srv srv
ln -s sysroot/ostree ostree
ln -s sysroot/tmp tmp

## save the new version number
echo -n "$newV" >etc/pine

mkdir -p etc/init.d
cat << 'EOF' >etc/init.d/vardirs
#!/sbin/openrc-run

description="Create targets for ostree deployments"

depend()
{
	need localmount
}

start() {
	ebegin "Setting dirs"
	mkdir -m 0755 -p /var/cache/rc /var/cache/apk /var/mnt /var/opt /var/srv /var/roothome /sysroot/ostree /sysroot/tmp
	ln -srnf /sysroot/home /var/home &>/dev/null
	eend $?
}

stop() {
	return
}
EOF
chmod +x etc/init.d/vardirs

cat << 'EOF' >etc/init.d/knobs
#!/sbin/openrc-run

description="Knobs customizations"

depend()
{
        need vardirs
}

start() {
        ebegin "Applying tweaks"

        ## misc
        knobs="madvise,/sys/kernel/mm/transparent_hugepage/enabled
madvise,/sys/kernel/mm/transparent_hugepage/defrag"

        for i in $knobs; do
                BIFS=$IFS; IFS=','
                set -- $i
                val=$1
                path=$2
                echo $val | tee $path &>/dev/null
                IFS=$BIFS
        done

        ## disks
        knobs="256,/queue/nr_requests
0,/queue/rotational
0,/queue/add_random
deadline,/queue/scheduler
4,/queue/iosched/writes_starved
8,/queue/iosched/fifo_batch
200,/queue/iosched/read_expire
4000,/queue/iosched/write_expire
4096,/queue/read_ahead_kb
4096,/queue/max_sectors_kb"

        BIFS=$IFS
        IFS=$'\n'
        eindent
        for b in `find /sys/block/ | grep -E "/vd.*|/sd.*"` ; do
                for i in $knobs; do
                        BIFS=$IFS; IFS=','
                        set -- $i
                        val=$1
                        path=$2
                        path=${b}${2}
                        eindent
                        if [ -f $path ] ; then
                                if ! $(echo $val > $path 2>/dev/null) ; then
                                        ewarn "${2} can't be applied"
                                fi
                        else
                                ewarn "${2} not available"
                        fi
                        eoutdent
                        IFS=$BIFS
                done
        done
        IFS=$BIFS

        ## net
        for i in `ifconfig | grep -Eo "^enp[0-9]*s[0-9]*|^eth[0-9]*"` ; do
                inff=$(ethtool -K $i tx on rx on tso on gro on lro on 2>&1)
                for l in $inff ; do
                        einfo "$l"
                done
                $(ip link set $i mtu 1500)
        done
        eoutdent
        eend $?
}

stop() {
        return
}
EOF
chmod +x etc/init.d/knobs

## mount-ro env var
mkdir -p etc/conf.d
echo "RC_NO_UMOUNTS=/usr" >etc/conf.d/mount-ro

## fstab
cat << EOF >etc/fstab
/dev/bd3                 /              xfs    rw,noatime,nodiratime,largeio,inode64,nobarrier     0  0
/dev/bd1                 /boot          xfs    rw,noexec,nodev,noatime,nodiratime,largeio,inode64  0  0
/dev/bd2                 swap           swap   defaults                                            0  0
/boot                    /sysroot/boot  none   bind                                                0  0
/ostree/deploy/pine/var  /var           none   bind                                                0  0
tmpfs                    /tmp           tmpfs  defaults,nosuid,nodev                               0  0
EOF

## repositories
mkdir -p etc/apk
cat << EOF >etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

## nameservers
cat << EOF >etc/resolv.conf
nameserver 8.8.8.8
nameserver 2001:4860:4860:0:0:0:0:8888
EOF

## net
mkdir -p etc/network
cat << EOF >etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
    hostname pine
EOF

## tunings
mkdir -p etc/sysctl.d
cat << EOF >etc/sysctl.d/01-grsec.conf
kernel.grsecurity.chroot_deny_fchdir=1
kernel.grsecurity.chroot_deny_shmat=1
kernel.grsecurity.chroot_deny_sysctl=1
kernel.grsecurity.chroot_deny_unix=1
kernel.grsecurity.chroot_enforce_chdir=1
kernel.grsecurity.chroot_findtask=1
##
kernel.grsecurity.chroot_caps=1
kernel.grsecurity.chroot_deny_chmod=1
kernel.grsecurity.chroot_deny_chroot=1
kernel.grsecurity.chroot_deny_mknod=1
kernel.grsecurity.chroot_deny_mount=1
kernel.grsecurity.chroot_deny_pivot=1
kernel.grsecurity.chroot_restrict_nice=1
kernel.pax.softmode=1
EOF
cat << EOF >etc/sysctl.d/02-tweaks.conf
## mem
vm.swappiness=10
vm.vfs_cache_pressure=40
vm.dirty_background_ratio=4
vm.dirty_ratio=80
vm.overcommit_memory=1
vm.overcommit_ratio=100
vm.min_free_kbytes=65536
kernel.pid_max=4194303
fs.file-max=6544018

## net
net.core.rmem_max=1677721600
net.core.rmem_default=167772160
net.core.wmem_max=1677721600
net.core.wmem_default=167772160
net.core.netdev_max_backlog=30000
net.core.somaxconn=16384
net.core.optmem_max=2048000
net.ipv4.tcp_mem=1024000 8738000 1677721600
net.ipv4.tcp_rmem=1024000 8738000 1677721600
net.ipv4.tcp_wmem=1024000 8738000 1677721600
net.ipv4.udp_mem=1024000 8738000 1677721600
net.ipv4.tcp_congestion_control=htcp
net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_sack=0
net.ipv4.tcp_dsack=0
net.ipv4.tcp_timestamps=0
net.ipv4.tcp_early_retrans=1
net.ipv4.tcp_app_win=40
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_no_metrics_save=1
EOF
mkdir -p etc/security/limits.d
cat << EOF >etc/security/limits.d/files.conf
*         hard    nofile      917504
*         soft    nofile      917504
root      hard    nofile      917504
root      soft    nofile      917504
EOF

## sudo
mkdir -p etc/sudoers.d
cat << EOF >etc/sudoers.d/pine
pine ALL=(ALL) NOPASSWD: ALL
EOF

mount --bind /sys sys
mount --bind /proc proc
mount --bind /dev dev

apkc() {
    apk --arch x86_64 --allow-untrusted --root $PWD --initdb add $@
}

apkc --update-cache alpine-base sudo tzdata  \
 mkinitfs grub-bios xfsprogs  \
 util-linux binutils coreutils blkid multipath-tools  \
 ca-certificates wget ethtool iptables  \
 ostree git  \
 htop iftop sysstat mosh-server tmux dropbear-ssh dropbear-scp

## fix for grub without syslinux
rm etc/grub.d/10_linux
## grub2 link for ostree compatibility
ln -sr usr/sbin/{grub-mkconfig,grub2-mkconfig}

## SETUP
chpwd() {
    chroot $PWD $@
}

hostname=pine
chpwd echo "root:rootppp" | chpwd chpasswd
chpwd adduser pine -D
chpwd echo "pine:pineppp" | chpwd chpasswd
echo '' >etc/motd
chpwd setup-hostname $hostname
chpwd setup-timezone -z CET
chpwd setup-sshd -c dropbear
chpwd setup-ntp -c busybox

## SERVICES
for r in `cat ../runlevels.pine`; do
    mkdir -p `dirname $r`
    ln -srf etc/init.d/`basename $r` `echo "$r" | sed 's#^/##'`
done

## UPDATES/REBOOTS
cp ../system-upgrade etc/periodic/daily
chmod +x etc/periodic/daily/system-upgrade

## GLIB
source ../glib.pine $PWD
source ../extras.pine

## BOOT
apkc --no-scripts linux-virtgrsec
patch usr/share/mkinitfs/initramfs-init ../initramfs-ostree.patch
chroot $PWD mkinitfs  \
 -F "ata base cdrom ext2 ext3 ext4 xfs keymap kms mmc raid scsi usb virtio"  \
 $(basename `ls -d lib/modules/*`)
mv boot tmpboot && mkdir boot
cp -a tmpboot/vmlinuz-virtgrsec boot/
cp -a tmpboot/initramfs-virtgrsec boot/
cksum=`cat boot/vmlinuz-virtgrsec boot/initramfs-virtgrsec | sha256sum | cut -f 1 -d ' '`
mv boot/vmlinuz-virtgrsec boot/vmlinuz-virtgrsec-${cksum}
mv boot/initramfs-virtgrsec boot/initramfs-virtgrsec-${cksum}
rm tmpboot -rf

## FIXES
rm -rf lib/rc/cache
ln -s /var/cache/rc lib/rc/cache

## CLEANUP
while `mountpoint -q ./proc`; do
    umount proc
done
while `mountpoint -q ./dev`; do
    umount dev
done
while `mountpoint -q ./sys`; do
    umount sys
done
rm dev var run etc -rf
mkdir -p dev var run usr/lib usr/bin usr/sbin
cp -a --remove-destination lib/* usr/lib
rm lib -rf && ln -s usr/lib lib
cp -a --remove-destination lib64/* usr/lib
rm lib64 -rf && ln -s usr/lib lib64
cp -a --remove-destination bin/* usr/bin
rm bin -rf && ln -s usr/bin bin
cp -a --remove-destination sbin/* usr/sbin
rm sbin -rf && ln -s usr/sbin sbin

## OSTREE
cd /srv
ostree --repo=pine commit -s $(date)'-build' -b trunk --tree=dir=tree
ostree summary -u --repo=pine
#pgrep -f trivial-httpd &>/dev/null || ostree trivial-httpd -P 39767 /srv/pine -d
