#!/bin/sh
source functions.pine

cat <<EOF > /etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

apk add --update-cache \
    bash \
	wget \
	git \
	unzip \
	xz \
	coreutils \
	blkid \
	binutils \
	multipath-tools \
	ca-certificates \
	util-linux \
	sfdisk \
	ostree \
	xfsprogs \
	go musl-dev `# for sup` \
	
## temporary grub command because grub is only in edge repo
apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/main -U grub-bios

source ./functions.pine
source ./glib.pine