#!/bin/sh -x
. ./functions.pine

## ostree workaround
ln -s /usr/sbin/grub-mkconfig /usr/sbin/grub2-mkconfig

apk --update-cache upgrade

apk add \
    bash \
	wget \
	curl \
	git \
	unzip \
	xz \
	coreutils \
	blkid \
	binutils \
	findutils \
	multipath-tools \
	ca-certificates \
	util-linux \
	sfdisk \
	ostree \
	grub-bios \
	xfsprogs \
	squashfs-tools \
	go musl-dev make linux-headers

. ./functions.pine
. ./glib.pine
