#!/bin/sh
. ./functions.pine

## prepare
printc "preparing..."
./prepare.pine

cat <<EOF >main_ex
. ./functions.pine
main() {
	## init the repo
	printc "initializing the repo..."
	./repo.pine

	## the tree of files
	printc "growing bare/kvm tree..."
	./make.pine
	printc "growing ovz tree..."
	./make_ovz.pine

	## update image from github
	printc "building image..."
	printc "$TRAVIS_COMMIT_MESSAGE"
	if [ "\${TRAVIS_COMMIT_MESSAGE/scratch-build}" != "\${TRAVIS_COMMIT_MESSAGE}" ]; then
		printc "this is a scratch build..."
		./init/build.pine
		printc "ovz..."
		./init/build_ovz.pine
	else
		printc "this is an updated build..."
		./build-update.pine
		printc "ovz..."
		./build-update_ovz.pine
	fi
}
main
EOF

mkfifo foo
stdbuf -o0 -e0 -i0 grep . foo | while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done &
stdbuf -o0 -e0 -i0 bash main_ex 2>foo
