#!/bin/sh
source functions.pine

main() {
	## prepare
	printc "preparing..."
	./prepare.pine

	## init the repo
	printc "initializing the repo..."
	./repo.pine

	## the tree of files
	printc "growing bare/kvm tree..."
	./make.pine
	printc "growing ovz tree..."
	./make_ovz.pine

	## update image from github
	printc "building image..."
	printc $TRAVIS_COMMIT_MESSAGE
	if [ $(echo "$TRAVIS_COMMIT_MESSAGE" | grep "scratch-build") ]; then
		printc "this is a scratch build..."
		./init/build.pine
		printc "ovz..."
		./init/build_ovz.pine
	else
		printc "this is an updated build..."
		./build-update.pine
		printc "ovz..."
		./build-update_ovz.pine
	fi
}

main 2> >(sed $'s,.*,\e[01;31m&\e[m,'>&2)