name: Pine Builder
'on':
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
      - run: . ./env.sh
      - run: >-
          docker run --env-file build.env -d --name pinect -v $PWD:/srv -v
          /dev:/dev -v /sys:/sys --privileged --cap-add=ALL -w /srv
          alpine:latest /bin/sleep 36000
      - run: docker exec pinect ./prepare.sh
      - run: docker exec pinect ./repo.sh
      - run: docker exec pinect ./make.sh
